name: Run integration tests

on:
  push:
    branches: [ "staging" ]

jobs:
  build_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Repo
      uses: actions/checkout@v4
    - name: Configure .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Retrieve packages
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Integration Tests
      run: dotnet test SoftUniBazar.Tests/SoftUniBazar.Tests.csproj --no-build --verbosity normal
